### ISSUE TITLE
can't find crate for `rustc_ast`

### ISSUE THREAD

**Issue by bamidev** [jdm/servo-embedding-example#4]
Good day!

So I've tried building the example on Windows again. This time I've ran into this error.
Interrestingly enough, I have ran into the same error months ago when I tried building the other embedding example.
I'm building it with the nightly toolchain.

```rustc
error[E0463]: can't find crate for `rustc_ast`
  --> C:\Users\lksdj\Projects\servo\components\script_plugins\lib.rs:22:1
   |
22 | extern crate rustc_ast;
   | ^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `script_plugins`
```

I'm not really familiar with the package. The `lib.rs` file which seems to break has this in it:
```rust
#![deny(unsafe_code)]
#![feature(plugin)]
#![feature(plugin_registrar)]
#![feature(rustc_private)]
#![cfg(feature = "unrooted_must_root_lint")]

extern crate rustc_ast;
extern crate rustc_driver;
extern crate rustc_hir;
extern crate rustc_lint;
extern crate rustc_middle;
extern crate rustc_session;
extern crate rustc_span;
```
I'm guessing that maybe the `rustc_private` feature should be responsible for enabling all the `rustc_*` crates.
Nevertheless, I don't really know why the crates are not available.

I can try on Linux as well to see if the problem exists there as well.

**Comment by okias** [comment]
same issue on linux. I can confirm.

**Comment by jdm** [comment]
You need to install the `rustc-dev` component through rustup.

**Comment by okias** [comment]
I tried look for native debian alternative (since I'm using `rustc/testing,unstable,now 1.48.0+dfsg1-1`) but I haven't found any.

I haven't found correspondenting `-dev` package in repository, do you have idea if there is anything install-able trough regular package manager?
Thank you

**Comment by jdm** [comment]
Sorry, we have no experience with other methods of using Rust besides rustup.

**Comment by bamidev** [comment]
> 
> 
> You need to install the `rustc-dev` component through rustup.

A great! Yes that worked. I couldn't find this anywhere on https://github.com/servo/servo/#setting-up-your-environment though...

Anyway, I've ran into another error, but it seems to be already stated over here: https://github.com/jdm/servo-embedding-example/issues/5
